#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= tq2440.o
obj-y	+= lowlevel_init.o
obj-$(CONFIG_SPL_BUILD) += nand_read_ll.o
